### ISSUE TITLE
Invalid go.mod

### ISSUE THREAD

**Issue by zi0r** [facundoolano/ngtop#17] opened 2024-07-31 16:12 UTC
Your go version definition in go.mod is invalid, which breaks some of the tooling:
`go: github.com/facundoolano/ngtop@latest (in github.com/facundoolano/ngtop@v0.0.0-20240731130445-2a2a4d9277a3): go.mod:3: invalid go version '1.22.4': must match format 1.23`

You need to change 1.22.4 to 1.22 to make it happy.

**Comment by facundoolano** [comment] 2024-07-31 16:23
What go version are you using? I'll look into this, but this go.mod was produced by `go mod init` with 1.22.4, so I'm assuming it should be valid at least for that go version. 

these issues seem related:
https://github.com/golang/go/issues/61888
https://github.com/golang/go/issues/63370

**Comment by facundoolano** [comment] 2024-07-31 16:26
and this https://github.com/golang/go/issues/61851

**Comment by facundoolano** [comment] 2024-09-14 19:28
Closing this at it seems to be the expected behavior on newer go versions (I can revisit if someone provides more context).

**Closed by facundoolano** 2024-09-14 19:28 UTC
